terraform {
  required_version = ">= 1.5.0"

  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

# 1–3: random resources
resource "random_id" "build_id" {
  byte_length = 4
}

resource "random_pet" "env_name" {
  length = 2
}

resource "random_integer" "replica_count" {
  min = 1
  max = 7
}

resource "random_integer" "replica_count-1" {
  min = 1
  max = 9
}
# 4–6: local files
resource "local_file" "config" {
  filename = "${path.module}/config.txt"
  content  = <<EOT
env      = ${random_pet.env_name.id}
build_id = ${random_id.build_id.hex}
replicas = ${random_integer.replica_count.result}
EOT
}

resource "local_file" "readme" {
  filename = "${path.module}/README.generated.md"
  content  = "Generated by Terraform at ${timestamp()}"
}

resource "local_file" "vars_dump" {
  filename = "${path.module}/vars.json"
  content  = jsonencode(var.settings)
}

# 7–9: null resources with triggers
resource "null_resource" "prepare" {
  triggers = {
    build_id = random_id.build_id.hex
  }
}

resource "null_resource" "validate" {
  depends_on = [null_resource.prepare]

  triggers = {
    checksum = sha256(local_file.config.content)
  }
}

resource "null_resource" "deploy" {
  depends_on = [null_resource.validate]

  triggers = {
    env = random_pet.env_name.id
  }
}

# 10: lifecycle behavior test
resource "null_resource" "immutable_example" {
  triggers = {
    version = var.app_version
  }

  lifecycle {
    create_before_destroy = true
  }
}

